
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (151,'Trindade ','2023-06-08','Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (189,'Faria Guimarães','2023-06-06','Não Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (198,'Lapa','2023-06-10','Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (203,'Trindade ','2023-06-14','Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (264,'Viso','2023-06-10','Não Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (298,'Senhora da Hora','2023-05-28','Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (326,'Bolhão','2023-06-13','Não Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (327,'Trindade ','2023-06-14','Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (387,'Senhora da Hora','2023-06-15','Não Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (419,'Lapa','2023-06-10','Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (442,'Bolhão','2023-06-01','Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (445,'Viso','2023-06-04','Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (503,'Faria Guimarães','2023-06-12','Não Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (517,'Trindade ','2023-06-07','Não Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (532,'Senhora da Hora','2023-05-13','Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (535,'Casa da Música','2023-06-15','Não Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (563,'Trindade ','2023-06-01','Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (586,'Bolhão','2023-06-15','Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (606,'Lapa','2023-06-14','Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (634,'Hospital de São João','2023-06-15','Não Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (669,'Bolhão','2023-06-01','Não Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (687,'Trindade','2023-06-11','Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (705,'Campo 24 de Agosto','2023-06-11','Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (717,'Senhora da Hora','2023-06-14','Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (748,'Bolhão','2023-06-14','Não Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (762,'Campanhã','2023-05-31','Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (785,'Trindade','2023-05-25','Não Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (812,'Campanhã','2023-06-07','Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (821,'Carolina Michaelis','2023-05-31','Não Validado');
INSERT INTO `Viagem` (`ViagemID`,`InicioViagem`,`DataViagem`,`Validacao`) VALUES (828,'Aeroporto','2023-06-09','Validado');
